name: learn-github-actions
run-name: ${{github.actor}} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version1:
    runs-on: ubintu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
  check-bats-version2:
    runs-on: ubintu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v