name: action-test
run-name: test-run
on: [push]
jobs: 
  job_1:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - run: pwd
     - run: ls -la
     - run: chmod 755 hello-echo.sh
     - run: ls -la
     - run: ./hello-echo.sh
